services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"     # DNS over TCP
      - "53:53/udp"     # DNS over UDP
      - "67:67/udp"     # DHCP (optional, if you use Pi-hole for DHCP)
      - "88:80/tcp"     # HTTP web interface
    environment:
      TZ: "America/Los_Angeles"   # Set to your local timezone
      WEBPASSWORD: "asdf" # Set a password for Pi-hole admin web UI
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
